hw6:
	javac -d . Iterator.java Collection.java Itr.java Set.java HashSet.java Duplicated.java List.java ArrayList.java Queue.java LinkedList.java QueueException.java NoElementException.java OutoftherangeException.java hw6.java
	javadoc *.java -d javadoc
	java hw6